### ISSUE TITLE
Bot labeled as APP in reaction overview

### ISSUE THREAD

**Issue by ronneycz** [FlurryShy/DiscordDeBrand#2]
Here again with another inconsistency/missed scenario.

![Screenshot_20240628_162855](https://github.com/FlurryShy/DiscordDeBrand/assets/40179235/91a27747-7828-4f28-8c9a-e4a506bf66cf)

And thank you for fixing the new profiles so quickly 🥇

**Comment by FlurryShy** [comment]
Am currently in the hospital, gonna fix it as soon as I can. probably early next week.

and the new profiles are atrocious, can't wait for a vencord plugin that will restore all roles and hopefully bio back to the popout. 👍

**Comment by FlurryShy** [comment]
Just an fyi... the "show all roles" plugin has been released on Vencord / Vesktop... 👍
