### ISSUE TITLE
Slash commands' argument boxes have wrong outline colour

### ISSUE THREAD

**Issue by ronneycz** [FlurryShy/DiscordDeBrand#3]
![Screenshot_20241023_070010](https://github.com/user-attachments/assets/15c43f42-ff08-412c-b60b-69c5ce476ef7)

**Comment by FlurryShy** [comment]
can't really replicate it atm... what color should it be? (good) old blurple?

This is on my end without any modifications:
![image](https://github.com/user-attachments/assets/5e0f57e4-95f5-4fb7-8da4-bf1afe705cc9)

**Comment by ronneycz** [comment]
I would make it good old blurple but even just your unmodified colour would be nice, no idea why it differs for us

**Comment by FlurryShy** [comment]
try and see if this works for you in quick-css, since I cannot replicate the issue:

```
div[class*="applicationCommand_"] > span[class*="selectedPill_"]{
    border-color: var(--brand-500) !important;
}
```

if it works I'll commit it to the theme.
also let me know which color would be better - old blurple or the one that is showing for me.
I don't really use / commands so I don't really care either way.

**Comment by ronneycz** [comment]
The quick-css thingy works and frankly, looks better to me than the default colour in your screenshot.

**Comment by FlurryShy** [comment]
pushed to the theme, should be available in a few minutes.
let me know if there are other things that need fixing - I usually only use very basic functions in Discord so I may miss things.
